### ISSUE TITLE
Problem running the training module in Wavenet tutorial.  What should I do?

### ISSUE THREAD

**Issue by shyamalschandra** [basveeling/wavenet#20]
```
iMac:wavenet shyamalsuhanachandra$ KERAS_BACKEND=theano python wavenet.py with small
Using Theano backend.
Traceback (most recent call last):
  File "wavenet.py", line 456, in <module>
    @ex.automain
  File "/usr/local/lib/python2.7/site-packages/sacred/experiment.py", line 109, in automain
    self.run_commandline()
  File "/usr/local/lib/python2.7/site-packages/sacred/experiment.py", line 203, in run_commandline
    args)
  File "/usr/local/lib/python2.7/site-packages/sacred/experiment.py", line 163, in run_command
    named_configs, force=force)
  File "/usr/local/lib/python2.7/site-packages/sacred/ingredient.py", line 310, in _create_run_for_command
    named_configs=named_configs, force=force)
  File "/usr/local/lib/python2.7/site-packages/sacred/initialize.py", line 301, in create_run
    scaffold.set_up_config()
  File "/usr/local/lib/python2.7/site-packages/sacred/initialize.py", line 107, in set_up_config
    fallback=self.fallback)
  File "/usr/local/lib/python2.7/site-packages/sacred/config/utils.py", line 74, in chain_evaluate_config_scopes
    fallback=fallback)
  File "/usr/local/lib/python2.7/site-packages/sacred/config/config_scope.py", line 64, in __call__
    .format(arg, available_entries))
KeyError: u"'desired_sample_rate' not in preset for ConfigScope. Available options are: set([])"
iMac:wavenet shyamalsuhanachandra$ KERAS_BACKEND=theano python wavenet.py with small
Using Theano backend.
Traceback (most recent call last):
  File "wavenet.py", line 456, in <module>
    @ex.automain
  File "/usr/local/lib/python2.7/site-packages/sacred/experiment.py", line 109, in automain
    self.run_commandline()
  File "/usr/local/lib/python2.7/site-packages/sacred/experiment.py", line 203, in run_commandline
    args)
  File "/usr/local/lib/python2.7/site-packages/sacred/experiment.py", line 163, in run_command
    named_configs, force=force)
  File "/usr/local/lib/python2.7/site-packages/sacred/ingredient.py", line 310, in _create_run_for_command
    named_configs=named_configs, force=force)
  File "/usr/local/lib/python2.7/site-packages/sacred/initialize.py", line 301, in create_run
    scaffold.set_up_config()
  File "/usr/local/lib/python2.7/site-packages/sacred/initialize.py", line 107, in set_up_config
    fallback=self.fallback)
  File "/usr/local/lib/python2.7/site-packages/sacred/config/utils.py", line 74, in chain_evaluate_config_scopes
    fallback=fallback)
  File "/usr/local/lib/python2.7/site-packages/sacred/config/config_scope.py", line 64, in __call__
    .format(arg, available_entries))
KeyError: u"'desired_sample_rate' not in preset for ConfigScope. Available options are: set([])"
```

The following output results from running the commands as advertised by the tutorial.  What changes do I need to make?  I compiled keras, Theano, and wavenet from source and ran into this problem.

**Comment by basveeling** [comment]
Thanks for the heads-up. I've pushed a fix that should solve this. Please let me know if you run into any more issues.
